version : '3.8'
services:
  redis-db:
    image: redis
    ports: 
      -"6379:6379"
  
  app-server:
    build: ./server
    ports:
      -"4000:4000"
    environment:
      - REIDS_URL=redis://redis-db:6379
    depends_on:
      - redis-db
